{% set name = "pigar" %}
{% set version = "0.9.0" %}
{% set sha256 = "2feb679abe7da1f583fcacbb518b86b5766d59300ddd3e5cf9f0f37ff625f0b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/damnever/pigar/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pigar = pigar.__main__:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - colorama==0.3.9
    - requests==2.18.4
    - futures  # [py2k]

test:
  imports:
    - pigar
  commands:
    - pigar --help

about:
  home: https://github.com/damnever/pigar
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    A fantastic tool to generate requirements for your Python project, and more
    than that.

extra:
  recipe-maintainers:
    - jakirkham
