{% set name = "pigar" %}
{% set version = "0.10.0" %}
{% set sha256 = "4f7a2887b20a41a08deb4eab29936093724bddb73c7f123f0a9dc6f9827d73a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pigar = pigar.__main__:main

requirements:
  host:
    - python
    - pip

  run:
    - python
    - colorama >=0.3.9
    - requests >=2.20.0
    - nbformat >=4.4.0
    - futures            # [py2k]

test:
  imports:
    - pigar
  commands:
    - pigar --help

about:
  home: https://github.com/damnever/pigar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    A fantastic tool to generate requirements for your Python project, and more
    than that.

extra:
  recipe-maintainers:
    - jakirkham
