{% set name = "pigar" %}
{% set version = "2.1.1" %}
{% set sha256 = "18dfa0daabbc23e5c14abca8b230c83e6a373ac37fadf2cee26b5a9bc9991fed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pigar-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - pigar=pigar.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=8.1
    - nbformat >=5.7
    - aiohttp >=3.8

test:
  imports:
    - pigar
  commands:
    - pip check
    - pigar --help
  requires:
    - pip

about:
  home: https://github.com/damnever/pigar
  summary: A fantastic tool to generate requirements for your Python project, and more than that.
  dev_url: https://github.com/damnever/pigar
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE
    - pigar/_vendor/pip/LICENSE.txt

extra:
  recipe-maintainers:
    - jakirkham
