{% set name = "pigar" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pigar-{{ version }}.tar.gz
  sha256: 870f43fc6da703fd9c62ed1a7f4a81ceb4e0336cce60be4c16bd7c3ebfe9f95b

build:
  entry_points:
    - pigar = pigar.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=69.0
    - wheel
    - pip
  run:
    - cryptography
    - docutils
    - pyopenssl
    - sphinx
    - python >={{ python_min }}
    - click >=8.1
    - nbformat >=5.7
    - aiohttp >=3.9
    - colorama

test:
  imports:
    - pigar
  commands:
    - pip check
    - pigar --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/damnever/pigar
  summary: A tool to generate requirements.txt for Python project.
  dev_url: https://github.com/damnever/pigar
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - pigar/_vendor/pip/LICENSE.txt

extra:
  recipe-maintainers:
    - jakirkham
    - rxm7706
