travis:
  secure:
    BINSTAR_TOKEN: oByPuuRIK2zn6ZsUZIaQP/1ErogYTQ1Z2vE5yynv0jBnp5WXpMVjICP0bfFD47jelSb5AtQtazO/MEGEANRP678m7SebXuH2qJJ9e5OwLcuulCRbcp+el2PxDHkh3iVnw0ifJi4ngV5h2G+3ETgu3ouWB97fGly1lPKk7Sm323kb0xHMh4rH6o3OjlYKS9++EhigqE/t34SstIGPWlZDUp9jcE+Lra8xuYR8JIYycNLj6Oy8C0AfM9Mk3MNGwkd7eHZex8igZ8cqgc98oEDoZ+PtK4NeLQ2vRolAVL1UWfzTxHlU8MEU4nXinvwa5ma9EszqFCmWcUX13UKgQOReIyTBZxhQTnxBfy+1+qVk5sspZ1tJHURrUjjFCm4/i/nzSIMxk+bmvcxOO3FxAKx8lvx5BMZBbxj9+91oZ0Y+zReMlY6s4Aa42S9BLOkE7S/cgJJIVO19j53Ew87CDRgzZ5OwuY0Mo5Us/XEBnJJCYUrgeOMXwBGzW9+rEIarbic3Yke8VHFszveXLDgto9ybOKBIEZ6sDhD4QkpyOv9KnmbnO4thED2BAzn1x/BJFSNy9jINg6iG5NFfB5ibumAib4t7jI4rDf/T7cuz1U+j87BPVA9NR3b7GcF3gWvU0VjQSWh95jZ4lzpHpu47Yle1uv2x6CBlpoESJClXI/7tIMU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
